#!/bin/bash
# Azel — Hyprland quick-toggle setup
# Sets up CTRL+SPACE to launch/toggle Azel as a floating scratchpad via Pyprland.
set -e

PYPR_CONFIG_DIR="$HOME/.config/pypr"
PYPR_CONFIG="$PYPR_CONFIG_DIR/config.toml"
HYPR_INCLUDE="$HOME/.config/hypr/azel.conf"
HYPR_MAIN="$HOME/.config/hypr/hyprland.conf"

echo "==> Checking for Hyprland..."
if ! command -v hyprctl &> /dev/null; then
    echo "Error: hyprctl not found. This script is only for Hyprland users."
    exit 1
fi

echo "==> Checking for azel binary..."
if ! command -v azel &> /dev/null; then
    echo "Error: 'azel' not found on PATH. Install Azel first (see README)."
    exit 1
fi

echo "==> Checking for pypr (Pyprland)..."
if ! command -v pypr &> /dev/null; then
    echo "Pyprland not found. Attempting install..."
    if command -v yay &> /dev/null; then
        yay -S --noconfirm pyprland
    elif command -v paru &> /dev/null; then
        paru -S --noconfirm pyprland
    elif command -v pip &> /dev/null; then
        pip install --user pyprland
    else
        echo "Error: no AUR helper (yay/paru) or pip found. Install Pyprland manually:"
        echo "  https://github.com/hyprland-community/pyprland"
        exit 1
    fi
fi

echo "==> Detecting Azel's actual window class..."
# Launch briefly to read its real class (case-sensitive), then close it.
azel &
AZEL_PID=$!
sleep 2
AZEL_CLASS=$(hyprctl clients -j | jq -r '.[] | select(.class | test("azel"; "i")) | .class' | head -n1)
kill "$AZEL_PID" 2>/dev/null || true

if [ -z "$AZEL_CLASS" ]; then
    echo "Warning: could not auto-detect Azel's window class. Defaulting to 'Azel'."
    AZEL_CLASS="Azel"
else
    echo "Detected window class: $AZEL_CLASS"
fi

echo "==> Writing Pyprland config..."
mkdir -p "$PYPR_CONFIG_DIR"
cat > "$PYPR_CONFIG" <<EOF
[pyprland]
plugins = ["scratchpads"]

[scratchpads.azel]
command = "env GDK_BACKEND=x11 azel"
class = "$AZEL_CLASS"
size = "40% 60%"
lazy = true
EOF

echo "==> Writing Hyprland include file ($HYPR_INCLUDE)..."
cat > "$HYPR_INCLUDE" <<EOF
# Azel quick-toggle (generated by install-hyprland.sh)
exec-once = pypr
bind = CTRL, SPACE, exec, pypr toggle azel

windowrule {
    match:class = ^($AZEL_CLASS)\$
    float = on
}
EOF

echo "==> Linking into your hyprland.conf..."
if ! grep -q "source = ~/.config/hypr/azel.conf" "$HYPR_MAIN" 2>/dev/null; then
    echo "" >> "$HYPR_MAIN"
    echo "source = ~/.config/hypr/azel.conf" >> "$HYPR_MAIN"
    echo "Added 'source = ~/.config/hypr/azel.conf' to your hyprland.conf"
else
    echo "Already sourced in hyprland.conf, skipping."
fi

echo "==> Reloading Hyprland..."
hyprctl reload

echo ""
echo "✅ Done! Press CTRL+SPACE to launch/toggle Azel."
echo "   (If pypr wasn't already running, log out and back in once so 'exec-once = pypr' takes effect.)"
